name: nix
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix-shell --run 'which go'
    - run: nix-build && ./result/bin/nix-search --help
  flakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command which go
    - run: nix build . && ./result/bin/nix-search --help
    - run: nix build .#nix-search && ./result/bin/nix-search --help
    - run: nix run . -- --help
    - run: nix run .#nix-search -- --help
    - run: nix flake check
  gomod2nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: nix develop --command gomod2nix
    - run: git diff-index --quiet HEAD -- && echo "gomod2nix had changes" && exit 1
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command nixpkgs-fmt --check *.nix
